[build]
command = "remix build"
publish = "public"

[dev]
command = "yarn watch"
port = 3000

[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
