[build]
  command = "pnpm run build"
  functions = "api/functions"
  publish = "dist"

[build.environment]
    NPM_FLAGS="--prefix=/"

[[redirects]]
  from = "/u/*"
  to = "/.netlify/functions/get_url?hash=:splat"
