name: Daily Netlify Deploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Node CI
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
            path: |
              ~/.pnpm-store
              node_modules
            key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-build-node_modules-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.8.0

      - name: Build website
        run: |
          pnpm install
          pnpm run build
        env:
            FAUNADB_SECRET: ${{ secrets.FAUNADB_SECRET }}

      - name: Upload to netlify
        uses: netlify/actions/cli@master
        with:
            args: deploy --prod
        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
